---
- hosts: localhost
  gather_facts: no
  become: yes

  vars:
    apps:
      - name: app1
        path: apps/app1
      # - name: app2
      #   path: apps/app2

  tasks:

    - name: Deploy apps
      community.docker.docker_compose_v2:
        project_src: "{{ item.path }}"
        state: present
      loop: "{{ apps }}"